title: Aidan Cone
logo: headshot.png
linkedin: https://www.linkedin.com/in/aidan-cone-28bb77212/
resume: https://personalmicrosoftsoftware0-my.sharepoint.com/:w:/g/personal/acone5_personalmicrosoftsoftware_ucla_edu/EeISEbGH3VFJp4vBCk8LX1IBESN62lGSFYRyJG0QzvQxVA?e=PXGG2n
show_downloads: false
theme: jekyll-theme-minimal
